[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
async-std = { workspace = true }

[dependencies.sea-orm-migration]
version = "1.1.0"
features = ["sqlx-mysql", "runtime-tokio"]
